/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInvoiceNoteRouteImport } from './routes/api/invoice-note'
import { Route as ApiJobLogRouteImport } from './routes/api/job-log'
import { Route as ApiYardRouteImport } from './routes/api/yard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceNoteRoute = ApiInvoiceNoteRouteImport.update({
  id: '/api/invoice-note',
  path: '/api/invoice-note',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobLogRoute = ApiJobLogRouteImport.update({
  id: '/api/job-log',
  path: '/api/job-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYardRoute = ApiYardRouteImport.update({
  id: '/api/yard',
  path: '/api/yard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/invoice-note': typeof ApiInvoiceNoteRoute
  '/api/job-log': typeof ApiJobLogRoute
  '/api/yard': typeof ApiYardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/invoice-note': typeof ApiInvoiceNoteRoute
  '/api/job-log': typeof ApiJobLogRoute
  '/api/yard': typeof ApiYardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/invoice-note': typeof ApiInvoiceNoteRoute
  '/api/job-log': typeof ApiJobLogRoute
  '/api/yard': typeof ApiYardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/invoice-note' | '/api/job-log' | '/api/yard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/invoice-note' | '/api/job-log' | '/api/yard'
  id: '__root__' | '/' | '/api/invoice-note' | '/api/job-log' | '/api/yard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiInvoiceNoteRoute: typeof ApiInvoiceNoteRoute
  ApiJobLogRoute: typeof ApiJobLogRoute
  ApiYardRoute: typeof ApiYardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice-note': {
      id: '/api/invoice-note'
      path: '/api/invoice-note'
      fullPath: '/api/invoice-note'
      preLoaderRoute: typeof ApiInvoiceNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/job-log': {
      id: '/api/job-log'
      path: '/api/job-log'
      fullPath: '/api/job-log'
      preLoaderRoute: typeof ApiJobLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yard': {
      id: '/api/yard'
      path: '/api/yard'
      fullPath: '/api/yard'
      preLoaderRoute: typeof ApiYardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiInvoiceNoteRoute: ApiInvoiceNoteRoute,
  ApiJobLogRoute: ApiJobLogRoute,
  ApiYardRoute: ApiYardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
